// src/data/imageData.js (o puedes ponerlo al principio del mismo componente)

export const imagesData = [
    { id: 'img1', src: '/images/mapaupn.png', alt: 'Mapa general UPNFM', category: 'I Edición, Campus Central UPNFM' },
    { id: 'imgm', src: '/images/mapagupnfmsps.png', alt: 'Mapa general UPNFM SPS', category: 'II Edición, CUR SPS' },
    { id: 'img2', src: '/images/gallery/fotob1.png', alt: 'Agua limpia', category: 'Módulos' },
    { id: 'img3', src: '/images/gallery/fotob2.png', alt: 'Ara Macao School, cierre El futuro del agua', category: 'I Edición, Campus Central UPNFM' },
    { id: 'img4', src: '/images/gallery/fotob3.png', alt: 'Autoridades, Agua para siempre', category: 'Módulos' },
    { id: 'img5', src: '/images/gallery/fotob4.png', alt: 'Autoridades, Agua para todas las personas', category: 'Módulos' },
    { id: 'img6', src: '/images/gallery/fotob5.png', alt: 'Autoridades, El planeta tiene sed', category: 'Módulos' },
    { id: 'img7', src: '/images/gallery/fotob6.png', alt: 'Autoridades, Agua limpia', category: 'Módulos' },
    { id: 'img8', src: '/images/gallery/fotob7.png', alt: 'Docentes, espacios instagrameables', category: 'I Edición, Campus Central UPNFM' },
    { id: 'img9', src: '/images/gallery/fotob8.png', alt: 'El planeta tiene sed', category: 'Módulos' },
    { id: 'img10', src: '/images/gallery/fotob9.png', alt: 'El planeta tiene sed', category: 'Módulos' },
    { id: 'img11', src: '/images/gallery/fotob10.png', alt: 'En bienvenida', category: 'I Edición, Campus Central UPNFM' },
    { id: 'img12', src: '/images/gallery/fotob11.png', alt: 'Estudiantes Ara School, Agua para siempre', category: 'I Edición, Campus Central UPNFM' },
    { id: 'img13', src: '/images/gallery/fotob12.png', alt: 'Instituto Hibueras, espacios instagrameables', category: 'I Edición, Campus Central UPNFM' },
    { id: 'img14', src: '/images/gallery/fotob13.png', alt: 'Estudiantes universitarios, Agua en movimiento', category: 'Módulos' },
    { id: 'img15', src: '/images/gallery/fotob14.png', alt: 'Estudiantes universitarios, Agua limpia', category: 'Módulos' },
    { id: 'img16', src: '/images/gallery/fotob15.png', alt: 'Estudiantes universitarios, Agua para siempre', category: 'Módulos' },
    { id: 'img17', src: '/images/gallery/fotob16.png', alt: 'Material del agua como derecho universal', category: 'I Edición, Campus Central UPNFM' },
    { id: 'img18', src: '/images/gallery/fotob17.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img19', src: '/images/gallery/fotob18.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img20', src: '/images/gallery/fotob19.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img21', src: '/images/gallery/fotob20.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img22', src: '/images/gallery/fotob21.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img23', src: '/images/gallery/fotob22.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img24', src: '/images/gallery/fotob23.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img25', src: '/images/gallery/fotob24.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img26', src: '/images/gallery/fotob25.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img27', src: '/images/gallery/fotob26.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img28', src: '/images/gallery/fotob27.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img29', src: '/images/gallery/fotob28.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img30', src: '/images/gallery/fotob29.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img31', src: '/images/gallery/fotob30.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img32', src: '/images/gallery/fotob31.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img33', src: '/images/gallery/fotob32.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img34', src: '/images/gallery/fotob33.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img35', src: '/images/gallery/fotob34.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img36', src: '/images/gallery/fotob35.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img37', src: '/images/gallery/fotob36.png', alt: 'Exposición itinerante SPS', category: 'II Edición, CUR SPS' },
    { id: 'img38', src: '/images/gallery/fotob37.png', alt: 'Exposición itinerante Danli', category: 'III Edición, CRU Danlí' },
    { id: 'img39', src: '/images/gallery/fotob38.png', alt: 'Exposición itinerante Danli', category: 'III Edición, CRU Danlí' },
    { id: 'img40', src: '/images/gallery/fotob39.png', alt: 'Exposición itinerante Danli', category: 'III Edición, CRU Danlí' },
    { id: 'img41', src: '/images/gallery/fotob40.png', alt: 'Exposición itinerante Danli', category: 'III Edición, CRU Danlí' },
    { id: 'img42', src: '/images/gallery/fotob41.png', alt: 'Exposición itinerante Danli', category: 'III Edición, CRU Danlí' },
    { id: 'img43', src: '/images/gallery/fotob42.png', alt: 'Exposición itinerante Danli', category: 'III Edición, CRU Danlí' },
    { id: 'img44', src: '/images/gallery/fotob43.png', alt: 'Exposición itinerante Danli', category: 'III Edición, CRU Danlí' },
    { id: 'img45', src: '/images/gallery/fotob44.png', alt: 'Exposición itinerante Danli', category: 'III Edición, CRU Danlí' },
    { id: 'img46', src: '/images/gallery/fotob45.png', alt: 'Exposición itinerante Danli', category: 'III Edición, CRU Danlí' },
    // Agrega más imágenes según tus necesidades
  ];
  
  // Extrae las categorías únicas para los botones de filtro
  export const categories = ['Todas', ...new Set(imagesData.map(img => img.category))];